In [34]:
import pandas as pd
import numpy as np

In [35]:
import pandas as pd

df = pd.read_csv("Cleaned dataset.csv", encoding="cp1252")

df.head()

,Rank,Previous Rank,Name,Country/Territory,Region,Size,Focus,Research,Status,Academic Reputation SCORE,...,founded,total_students,intl_students_pct,nobel_laureates,fields_medalists,ranked_in_all_3,avg_rank_all3,university_age_2026,data_sources,university_type
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,1861,11858,34,100,1,1,2.0,165,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Private
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,1907,19000,61,15,0,0,5.0,119,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Public
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,1885,17249,24,85,22,1,3.3,141,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Private
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,1096,24000,41,72,0,1,3.7,930,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Public
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,1636,21000,25,162,4,1,3.7,390,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Private

In [36]:
df.head()

,Rank,Previous Rank,Name,Country/Territory,Region,Size,Focus,Research,Status,Academic Reputation SCORE,...,founded,total_students,intl_students_pct,nobel_laureates,fields_medalists,ranked_in_all_3,avg_rank_all3,university_age_2026,data_sources,university_type
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,1861,11858,34,100,1,1,2.0,165,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Private
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,1907,19000,61,15,0,0,5.0,119,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Public
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,1885,17249,24,85,22,1,3.3,141,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Private
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,1096,24000,41,72,0,1,3.7,930,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Public
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,1636,21000,25,162,4,1,3.7,390,QS Jun-2025 | THE Oct-2025 | ARWU Aug-2025,Private

In [37]:
df.shape

(200, 49)

In [38]:
df.columns

Index(['Rank', 'Previous Rank', 'Name', 'Country/Territory', 'Region', 'Size',
       'Focus', 'Research', 'Status', 'Academic Reputation SCORE',
       'Academic Reputation  RANK', 'Employer Reputation SCORE',
       'Employer Reputation RANK', 'Faculty Student Ratio SCORE',
       'Faculty Student Ratio RANK', 'Citations per Faculty SCORE',
       'Citations per Faculty RANK', 'International Faculty  SCORE',
       'International Faculty  RANK', 'International Student SCORE',
       'International student  RANK', 'International Students Diversity SCORE',
       'International Students Diversity RANK',
       'International Research Network SCORE',
       'International Research Network RANK', 'Employment Outcomes SCORE',
       'Employment Outcomes RANK', 'Sustainability SCORE',
       'Sustainability RANK', 'Overall SCORE', 'the_rank_2026',
       'arwu_rank_2025', 'the_score', 'arwu_score', 'the_teaching',
       'the_research_env', 'the_research_quality', 'the_industry',
       'the_intl_outlook', 'founded', 'total_students', 'intl_students_pct',
       'nobel_laureates', 'fields_medalists', 'ranked_in_all_3',
       'avg_rank_all3', 'university_age_2026', 'data_sources',
       'university_type'],
      dtype='str')

In [39]:
df.dtypes

Rank                                        int64
Previous Rank                               int64
Name                                          str
Country/Territory                             str
Region                                        str
Size                                          str
Focus                                         str
Research                                      str
Status                                        str
Academic Reputation SCORE                 float64
Academic Reputation  RANK                   int64
Employer Reputation SCORE                 float64
Employer Reputation RANK                    int64
Faculty Student Ratio SCORE               float64
Faculty Student Ratio RANK                  int64
Citations per Faculty SCORE               float64
Citations per Faculty RANK                  int64
International Faculty  SCORE              float64
International Faculty  RANK                 int64
International Student SCORE               float64
International student  RANK                 int64
International Students Diversity SCORE    float64
International Students Diversity RANK       int64
International Research Network SCORE      float64
International Research Network RANK         int64
Employment Outcomes SCORE                 float64
Employment Outcomes RANK                    int64
Sustainability SCORE                      float64
Sustainability RANK                           str
Overall SCORE                             float64
the_rank_2026                               int64
arwu_rank_2025                              int64
the_score                                 float64
arwu_score                                float64
the_teaching                              float64
the_research_env                          float64
the_research_quality                      float64
the_industry                              float64
the_intl_outlook                          float64
founded                                     int64
total_students                              int64
intl_students_pct                           int64
nobel_laureates                             int64
fields_medalists                            int64
ranked_in_all_3                             int64
avg_rank_all3                             float64
university_age_2026                         int64
data_sources                                  str
university_type                               str
dtype: object

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 49 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Rank                                    200 non-null    int64
 1   Previous Rank                           200 non-null    int64
 2   Name                                    200 non-null    str
 3   Country/Territory                       200 non-null    str
 4   Region                                  200 non-null    str
 5   Size                                    200 non-null    str
 6   Focus                                   200 non-null    str
 7   Research                                200 non-null    str
 8   Status                                  200 non-null    str
 9   Academic Reputation SCORE               200 non-null    float64
 10  Academic Reputation  RANK               200 non-null    int64
 11  Employer Reputation SCORE               200 non-null    float64
 12  Employer Reputation RANK                200 non-null    int64
 13  Faculty Student Ratio SCORE             200 non-null    float64
 14  Faculty Student Ratio RANK              200 non-null    int64
 15  Citations per Faculty SCORE             200 non-null    float64
 16  Citations per Faculty RANK              200 non-null    int64
 17  International Faculty  SCORE            200 non-null    float64
 18  International Faculty  RANK             200 non-null    int64
 19  International Student SCORE             200 non-null    float64
 20  International student  RANK             200 non-null    int64
 21  International Students Diversity SCORE  200 non-null    float64
 22  International Students Diversity RANK   200 non-null    int64
 23  International Research Network SCORE    200 non-null    float64
 24  International Research Network RANK     200 non-null    int64
 25  Employment Outcomes SCORE               200 non-null    float64
 26  Employment Outcomes RANK                200 non-null    int64
 27  Sustainability SCORE                    200 non-null    float64
 28  Sustainability RANK                     200 non-null    str
 29  Overall SCORE                           200 non-null    float64
 30  the_rank_2026                           200 non-null    int64
 31  arwu_rank_2025                          200 non-null    int64
 32  the_score                               200 non-null    float64
 33  arwu_score                              200 non-null    float64
 34  the_teaching                            200 non-null    float64
 35  the_research_env                        200 non-null    float64
 36  the_research_quality                    200 non-null    float64
 37  the_industry                            200 non-null    float64
 38  the_intl_outlook                        200 non-null    float64
 39  founded                                 200 non-null    int64
 40  total_students                          200 non-null    int64
 41  intl_students_pct                       200 non-null    int64
 42  nobel_laureates                         200 non-null    int64
 43  fields_medalists                        200 non-null    int64
 44  ranked_in_all_3                         200 non-null    int64
 45  avg_rank_all3                           200 non-null    float64
 46  university_age_2026                     200 non-null    int64
 47  data_sources                            200 non-null    str
 48  university_type                         200 non-null    str
dtypes: float64(19), int64(20), str(10)
memory usage: 99.2 KB

In [41]:
df.isnull().sum()

Rank                                      0
Previous Rank                             0
Name                                      0
Country/Territory                         0
Region                                    0
Size                                      0
Focus                                     0
Research                                  0
Status                                    0
Academic Reputation SCORE                 0
Academic Reputation  RANK                 0
Employer Reputation SCORE                 0
Employer Reputation RANK                  0
Faculty Student Ratio SCORE               0
Faculty Student Ratio RANK                0
Citations per Faculty SCORE               0
Citations per Faculty RANK                0
International Faculty  SCORE              0
International Faculty  RANK               0
International Student SCORE               0
International student  RANK               0
International Students Diversity SCORE    0
International Students Diversity RANK     0
International Research Network SCORE      0
International Research Network RANK       0
Employment Outcomes SCORE                 0
Employment Outcomes RANK                  0
Sustainability SCORE                      0
Sustainability RANK                       0
Overall SCORE                             0
the_rank_2026                             0
arwu_rank_2025                            0
the_score                                 0
arwu_score                                0
the_teaching                              0
the_research_env                          0
the_research_quality                      0
the_industry                              0
the_intl_outlook                          0
founded                                   0
total_students                            0
intl_students_pct                         0
nobel_laureates                           0
fields_medalists                          0
ranked_in_all_3                           0
avg_rank_all3                             0
university_age_2026                       0
data_sources                              0
university_type                           0
dtype: int64

In [42]:
(df.isnull().sum() / len(df)) * 100

Rank                                      0.0
Previous Rank                             0.0
Name                                      0.0
Country/Territory                         0.0
Region                                    0.0
Size                                      0.0
Focus                                     0.0
Research                                  0.0
Status                                    0.0
Academic Reputation SCORE                 0.0
Academic Reputation  RANK                 0.0
Employer Reputation SCORE                 0.0
Employer Reputation RANK                  0.0
Faculty Student Ratio SCORE               0.0
Faculty Student Ratio RANK                0.0
Citations per Faculty SCORE               0.0
Citations per Faculty RANK                0.0
International Faculty  SCORE              0.0
International Faculty  RANK               0.0
International Student SCORE               0.0
International student  RANK               0.0
International Students Diversity SCORE    0.0
International Students Diversity RANK     0.0
International Research Network SCORE      0.0
International Research Network RANK       0.0
Employment Outcomes SCORE                 0.0
Employment Outcomes RANK                  0.0
Sustainability SCORE                      0.0
Sustainability RANK                       0.0
Overall SCORE                             0.0
the_rank_2026                             0.0
arwu_rank_2025                            0.0
the_score                                 0.0
arwu_score                                0.0
the_teaching                              0.0
the_research_env                          0.0
the_research_quality                      0.0
the_industry                              0.0
the_intl_outlook                          0.0
founded                                   0.0
total_students                            0.0
intl_students_pct                         0.0
nobel_laureates                           0.0
fields_medalists                          0.0
ranked_in_all_3                           0.0
avg_rank_all3                             0.0
university_age_2026                       0.0
data_sources                              0.0
university_type                           0.0
dtype: float64

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df = df.drop_duplicates()

In [45]:
numeric_cols = df.select_dtypes(include=np.number).columns

df[numeric_cols] = df[numeric_cols].fillna(
    df[numeric_cols].median()
)

In [46]:
categorical_cols = df.select_dtypes(include="object").columns

for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

C:\Users\Vanjari Pragathi\AppData\Local\Temp\ipykernel_24852\3309253727.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include="object").columns

In [47]:
df.isnull().sum()

Rank                                      0
Previous Rank                             0
Name                                      0
Country/Territory                         0
Region                                    0
Size                                      0
Focus                                     0
Research                                  0
Status                                    0
Academic Reputation SCORE                 0
Academic Reputation  RANK                 0
Employer Reputation SCORE                 0
Employer Reputation RANK                  0
Faculty Student Ratio SCORE               0
Faculty Student Ratio RANK                0
Citations per Faculty SCORE               0
Citations per Faculty RANK                0
International Faculty  SCORE              0
International Faculty  RANK               0
International Student SCORE               0
International student  RANK               0
International Students Diversity SCORE    0
International Students Diversity RANK     0
International Research Network SCORE      0
International Research Network RANK       0
Employment Outcomes SCORE                 0
Employment Outcomes RANK                  0
Sustainability SCORE                      0
Sustainability RANK                       0
Overall SCORE                             0
the_rank_2026                             0
arwu_rank_2025                            0
the_score                                 0
arwu_score                                0
the_teaching                              0
the_research_env                          0
the_research_quality                      0
the_industry                              0
the_intl_outlook                          0
founded                                   0
total_students                            0
intl_students_pct                         0
nobel_laureates                           0
fields_medalists                          0
ranked_in_all_3                           0
avg_rank_all3                             0
university_age_2026                       0
data_sources                              0
university_type                           0
dtype: int64

In [48]:
df.describe()

,Rank,Previous Rank,Academic Reputation SCORE,Academic Reputation RANK,Employer Reputation SCORE,Employer Reputation RANK,Faculty Student Ratio SCORE,Faculty Student Ratio RANK,Citations per Faculty SCORE,Citations per Faculty RANK,...,the_industry,the_intl_outlook,founded,total_students,intl_students_pct,nobel_laureates,fields_medalists,ranked_in_all_3,avg_rank_all3,university_age_2026
count,200.00000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.00000,200.000000,...,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.00000,200.0000,200.000000,200.000000
mean,100.23500,102.200000,76.458000,116.120000,73.504500,150.435000,54.419500,403.240000,68.55500,249.845000,...,66.704500,69.906500,1828.110000,35278.875000,30.900000,27.880000,0.98000,0.0900,38.100500,197.890000
std,57.80299,59.982074,18.642814,81.030955,22.063978,126.152559,30.648195,278.694773,24.42216,194.267574,...,5.256537,6.340189,86.631188,10887.559011,7.859955,19.327789,1.63492,0.2869,21.886497,86.631188
min,1.00000,1.000000,34.000000,1.000000,20.700000,1.000000,5.200000,5.000000,2.10000,1.000000,...,34.400000,40.400000,1096.000000,2240.000000,3.000000,0.000000,0.00000,0.0000,2.000000,11.000000
25%,50.75000,50.000000,61.450000,50.750000,56.250000,51.500000,29.000000,147.000000,54.12500,103.500000,...,66.700000,69.900000,1828.000000,35279.000000,31.000000,28.000000,1.00000,0.0000,38.100000,198.000000
50%,100.50000,102.000000,76.300000,105.500000,75.700000,122.500000,50.100000,381.500000,70.90000,209.500000,...,66.700000,69.900000,1828.000000,35279.000000,31.000000,28.000000,1.00000,0.0000,38.100000,198.000000
75%,150.25000,150.500000,93.325000,165.250000,94.550000,211.250000,83.975000,650.750000,89.75000,340.750000,...,66.700000,69.900000,1828.000000,35279.000000,31.000000,28.000000,1.00000,0.0000,38.100000,198.000000
max,199.00000,227.000000,100.000000,357.000000,100.000000,639.000000,100.000000,801.000000,100.00000,801.000000,...,80.400000,100.000000,2015.000000,97000.000000,72.000000,162.000000,22.00000,1.0000,234.500000,930.000000

In [49]:
df = df.rename(columns={
    "total_students": "Total_Students",
    "intl_students_pct": "International_Students_Percentage"
})

In [50]:
df["founded"] = pd.to_numeric(df["founded"], errors="coerce")

In [51]:
# Data Transformation

In [52]:
df["university_age"] = 2026 - df["founded"]

In [53]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(r"\s+", "_", regex=True)

In [54]:
print(df.columns.tolist())

['Rank', 'Previous_Rank', 'Name', 'Country/Territory', 'Region', 'Size', 'Focus', 'Research', 'Status', 'Academic_Reputation_SCORE', 'Academic_Reputation_RANK', 'Employer_Reputation_SCORE', 'Employer_Reputation_RANK', 'Faculty_Student_Ratio_SCORE', 'Faculty_Student_Ratio_RANK', 'Citations_per_Faculty_SCORE', 'Citations_per_Faculty_RANK', 'International_Faculty_SCORE', 'International_Faculty_RANK', 'International_Student_SCORE', 'International_student_RANK', 'International_Students_Diversity_SCORE', 'International_Students_Diversity_RANK', 'International_Research_Network_SCORE', 'International_Research_Network_RANK', 'Employment_Outcomes_SCORE', 'Employment_Outcomes_RANK', 'Sustainability_SCORE', 'Sustainability_RANK', 'Overall_SCORE', 'the_rank_2026', 'arwu_rank_2025', 'the_score', 'arwu_score', 'the_teaching', 'the_research_env', 'the_research_quality', 'the_industry', 'the_intl_outlook', 'founded', 'Total_Students', 'International_Students_Percentage', 'nobel_laureates', 'fields_medalists', 'ranked_in_all_3', 'avg_rank_all3', 'university_age_2026', 'data_sources', 'university_type', 'university_age']

In [55]:
df["Overall_Score_Normalized"] = (
    (df["Overall_SCORE"] - df["Overall_SCORE"].min()) /
    (df["Overall_SCORE"].max() - df["Overall_SCORE"].min())
)

In [56]:
df[["Overall_SCORE", "Overall_Score_Normalized"]].head()

   Overall_SCORE  Overall_Score_Normalized
0          100.0                  1.000000
1           99.4                  0.986456
2           98.9                  0.975169
3           97.9                  0.952596
4           97.7                  0.948081

In [57]:
df["Performance_Category"] = pd.cut(
    df["Overall_SCORE"],
    bins=[0, 40, 60, 80, 100],
    labels=["Low", "Moderate", "Good", "Excellent"]
)

In [58]:
df[["Name", "Overall_SCORE", "Performance_Category"]].head(10)

,Name,Overall_SCORE,Performance_Category
0,Massachusetts Institute of Technology (MIT),100.0,Excellent
1,Imperial College London,99.4,Excellent
2,Stanford University,98.9,Excellent
3,University of Oxford,97.9,Excellent
4,Harvard University,97.7,Excellent
5,University of Cambridge,97.2,Excellent
6,ETH Zurich (Swiss Federal Institute of Technol...,96.7,Excellent
7,National University of Singapore (NUS),95.9,Excellent
8,UCL (University College London),95.8,Excellent
9,California Institute of Technology (Caltech),94.3,Excellent

In [59]:
df["Performance_Category"].value_counts()

Performance_Category
Good         106
Excellent     59
Moderate      35
Low            0
Name: count, dtype: int64

In [60]:
df["Rank_Category"] = pd.cut(
    df["Rank"],
    bins=[0, 10, 50, 100, 500, float("inf")],
    labels=[
        "Top 10",
        "Top 50",
        "Top 100",
        "Top 500",
        "Below 500"
    ]
)

In [61]:
df[["Name", "Rank", "Rank_Category"]].head(10)

                                                Name  Rank Rank_Category
0        Massachusetts Institute of Technology (MIT)     1        Top 10
1                            Imperial College London     2        Top 10
2                                Stanford University     3        Top 10
3                               University of Oxford     4        Top 10
4                                 Harvard University     5        Top 10
5                            University of Cambridge     6        Top 10
6  ETH Zurich (Swiss Federal Institute of Technol...     7        Top 10
7             National University of Singapore (NUS)     8        Top 10
8                    UCL (University College London)     9        Top 10
9       California Institute of Technology (Caltech)    10        Top 10

In [62]:
for col in ["the_score", "arwu_score"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")
    
    df[col + "_Normalized"] = (
        (df[col] - df[col].min()) /
        (df[col].max() - df[col].min())
    )

In [63]:
df[
    [
        "the_score",
        "the_score_Normalized",
        "arwu_score",
        "arwu_score_Normalized"
    ]
].head()

   the_score  the_score_Normalized  arwu_score  arwu_score_Normalized
0       96.4              0.988142       100.0               1.000000
1       86.1              0.784585        65.1               0.475976
2       95.5              0.970356        76.5               0.647147
3       97.0              1.000000        72.4               0.585586
4       95.5              0.970356       100.0               1.000000

In [64]:
df.to_csv("Transformed_University_Dataset.csv", index=False)
print("Dataset cleaned successfully")

Dataset cleaned successfully

In [65]:
print(df.columns.tolist())

['Rank', 'Previous_Rank', 'Name', 'Country/Territory', 'Region', 'Size', 'Focus', 'Research', 'Status', 'Academic_Reputation_SCORE', 'Academic_Reputation_RANK', 'Employer_Reputation_SCORE', 'Employer_Reputation_RANK', 'Faculty_Student_Ratio_SCORE', 'Faculty_Student_Ratio_RANK', 'Citations_per_Faculty_SCORE', 'Citations_per_Faculty_RANK', 'International_Faculty_SCORE', 'International_Faculty_RANK', 'International_Student_SCORE', 'International_student_RANK', 'International_Students_Diversity_SCORE', 'International_Students_Diversity_RANK', 'International_Research_Network_SCORE', 'International_Research_Network_RANK', 'Employment_Outcomes_SCORE', 'Employment_Outcomes_RANK', 'Sustainability_SCORE', 'Sustainability_RANK', 'Overall_SCORE', 'the_rank_2026', 'arwu_rank_2025', 'the_score', 'arwu_score', 'the_teaching', 'the_research_env', 'the_research_quality', 'the_industry', 'the_intl_outlook', 'founded', 'Total_Students', 'International_Students_Percentage', 'nobel_laureates', 'fields_medalists', 'ranked_in_all_3', 'avg_rank_all3', 'university_age_2026', 'data_sources', 'university_type', 'university_age', 'Overall_Score_Normalized', 'Performance_Category', 'Rank_Category', 'the_score_Normalized', 'arwu_score_Normalized']

In [66]:
# ==============================
# KPI CALCULATIONS
# ==============================

# 1. Total number of universities
total_universities = df["Name"].nunique()

# 2. Average overall score
average_score = df["Overall_SCORE"].mean()

# 3. Highest overall score
highest_score = df["Overall_SCORE"].max()

# 4. Average QS rank
average_rank = df["Rank"].mean()

# 5. Average international students percentage
average_international_students = df["International_Students_Percentage"].mean()

# 6. Average university age
average_university_age = df["university_age"].mean()

# 7. Number of Top 10 universities
top_10_count = (df["Rank"] <= 10).sum()

# 8. Universities ranked in all 3 ranking systems
ranked_all_3 = df["ranked_in_all_3"].sum()


# ==============================
# CREATE KPI TABLE
# ==============================

kpis = {
    "Total Universities": total_universities,
    "Average Overall Score": round(average_score, 2),
    "Highest Overall Score": round(highest_score, 2),
    "Average QS Rank": round(average_rank, 2),
    "Average International Students %": round(average_international_students, 2),
    "Average University Age": round(average_university_age, 2),
    "Top 10 Universities": top_10_count,
    "Universities Ranked in All 3": ranked_all_3
}

kpi_table = pd.DataFrame(
    list(kpis.items()),
    columns=["KPI", "Value"]
)

kpi_table

                                KPI   Value
0                Total Universities  200.00
1             Average Overall Score   72.20
2             Highest Overall Score  100.00
3                   Average QS Rank  100.24
4  Average International Students %   30.90
5            Average University Age  197.89
6               Top 10 Universities   10.00
7      Universities Ranked in All 3   18.00